#!/bin/sh

user=$(cat "$__object/parameter/user")
home=$(cat "$__object/parameter/home"); [ -z "$home" ] && home="/home/$user"

bindir=$home/bin

require="$require __user/$user" __directory $bindir
for f in $__type/files/*; do
	require="$require __directory/$bindir" \
	__file $bindir/$(basename $f) --source $f --owner $user --mode 755
done

__git $bindir/eisenmux --source https://github.com/niknow/eisenmux.git --owner $user
