#!/bin/sh

user=$(cat "$__object/parameter/user")
netzh_id=$(cat "$__object/parameter/netzh-id" 2>/dev/null || echo "$__object_id")

##### memcached #############################################################

__package memcached
require="$require __package/memcached" __start_on_boot memcached --state absent

##### memtier ###############################################################

memtier_repo="/home/$user/memtier"
memtier_url="https://github.com/RedisLabs/memtier_benchmark.git"

for pkg in build-essential autoconf automake libpcre3-dev libevent-dev pkg-config zlib1g-dev; do
    __package $pkg
done

__git $memtier_repo --source $memtier_url --owner $user

##### my middleware #########################################################

__file /home/$user/middleware.jar --owner $user --source /home/kamila/u/school/asl/build/dist/middleware-${netzh_id}.jar

##### utilities #############################################################

__package pv

# __apt_source azure-cli \
# 	--uri https://packages.microsoft.com/repos/azure-cli/ \
# 	--distribution wheezy \
# 	--component main

# __package apt-transport-https
# require="$require __package/apt-transport-https __apt_source/azure-cli __apt_key_uri/azure-cli" __package azure-cli
