#!/bin/sh

# TODO clean up as it grows, when it becomes easier to see how to organize this

user=$(cat "$__object/parameter/user")
home=$(cat "$__object/parameter/home"); [ -z "$home" ] && home="/home/$user"

if [ -f "$__object/parameter/graphical" ]; then
	export EDITOR=subl
else
	export EDITOR=vim
fi

if [ -f "$__object/parameter/with-emacs" ]; then
	export EDITOR="emacsclient -c"

	__directory   $home/.local/share/applications/ --parents
	require="$require __directory/$home/.local/share/applications/" \
		__config_file $home/.local/share/applications/emacsclient_new_frame.desktop \
		  --owner $user --source $__type/files/emacsclient_new_frame.desktop
fi

$__type/files/profile.sh | __config_file $home/.profile --owner $user --source -
__config_file $home/.config/i3/config  --owner $user --source $__type/files/i3-config
__config_file $home/.xbindkeysrc       --owner $user --source $__type/files/xbindkeysrc
__config_file $home/.gitconfig         --owner $user --source $__type/files/gitconfig
__config_file $home/.stack/config.yaml --owner $user --source $__type/files/stack-config.yaml

__kamila_fish_config --user "$user" --home "$home"
__kamila_task_config --user "$user" --home "$home"
__ssh_config_from_inventory --user $user --home $home
