#!/bin/sh

case $__target_host in
	*ungleich*)
		echo 'Nope.' >&2
		exit 47
	;;
esac

. $__manifest/secrets

is_jailed=$(cat $__global/explorer/is-freebsd-jail)
os=$(cat $__global/explorer/os)

__cdistmarker
[ "$is_jailed"      ] || __hostname
[ "$os" = 'freebsd' ] || __locale "en_US.UTF-8"

case $__target_host in
	entropy)
		__kamila_home --size graphical
		# __ethz_asl_host skamila --user kamila
	;;

	home)
		__kamila_home --size extra
	;;

	rpi)
		__kamila_home --size cozy

		__miredo
		__ipv6_ddns brloh.dynv6.net --token $DYNV6_TOKEN --device teredo
		__cron savetheplants --user root \
			--command 'gpioctl -c 17 OUT; gpioctl 17 1 ; sleep 20; gpioctl 17 0' \
			--minute '15' --hour '13' --day_of_week '1,5'
	;;

	ev3)
		__kamila_home --size cozy --user robot
		__file /etc/systemd/system/ev3dev-leds.service --source $__manifest/files/ev3dev-leds.service
	;;

	asl*)
		__kamila_home --size cozy
		require="$require __kamila_home" __ethz_asl_host skamila --user kamila
	;;
	foraslvms*)
		__ethz_asl_host skamila --user skamila
	;;

	monitoring-playground)
		__kamila_home --size cozy
	;;

esac
