#!/bin/sh

case $__target_host in
	*ungleich*)
		echo 'Nope.' >&2
		exit 47
	;;
esac


__cdistmarker
__hostname
__locale "en_US.UTF-8"
__locale "de_CH.UTF-8"
if [ -z "$CDIST_NO_PACKAGE_INDEX_UPDATE" ]; then
	case $(cat $__explorer/os) in
		debian|ubuntu|devuan)
			__apt_update_index
			export require="$require __apt_update_index"
		;;
	esac
fi

case $__target_host in
	entropy)
		__kamila_home --size graphical
		__ethz_asl_host skamila --user kamila  # for now
	;;

	ev3)
		__kamila_home --size cozy --user robot
		__file /etc/systemd/system/ev3dev-leds.service --source $__manifest/files/ev3dev-leds.service
	;;

	asl*)
		__kamila_home --size cozy
		__ethz_asl_host skamila --user kamila
	;;

esac
