#!/bin/sh

case $__target_host in
	*ungleich*)
		echo 'Nope.' >&2
		exit 47
	;;
esac

is_jailed=$(cat $__global/explorer/is-jailed)
os=$(cat $__global/explorer/os)

__cdistmarker
[ "$is_jailed"      ] || __hostname
[ "$os" = 'freebsd' ] || __locale "en_US.UTF-8"
[ "$os" = 'freebsd' ] || __locale "de_CH.UTF-8"

if [ -z "$CDIST_NO_PACKAGE_INDEX_UPDATE" ]; then
	case $os in
		debian|ubuntu|devuan)
			__apt_update_index
			export require="$require __apt_update_index"
		;;
	esac
fi

case $__target_host in
	entropy)
		__kamila_home --size graphical
		# __ethz_asl_host skamila --user kamila  # for now
	;;

	home)
		__kamila_home --size extra
	;;

	ev3)
		__kamila_home --size cozy --user robot
		__file /etc/systemd/system/ev3dev-leds.service --source $__manifest/files/ev3dev-leds.service
	;;

	asl*)
		__kamila_home --size cozy
		require="$require __kamila_home" __ethz_asl_host skamila --user kamila
	;;
	foraslvms*)
		__ethz_asl_host skamila --user skamila
	;;

esac
